// Talent tree definitions for Phase 12

export interface TalentNode {
  id: string;
  name: string;
  description: string;
  branch: string;
  tier: number;
  maxRank: number;
  pointsInBranchRequired: number;
  levelRequired: number;
  prerequisiteTalents?: string[];
  effects: Record<string, any>;
  grantsSkill?: string;
}

export interface TalentBranch {
  id: string;
  name: string;
  description: string;
  talents: TalentNode[];
}

export const SCRAP_ENGINEER_TALENTS: TalentBranch[] = [
  {
    id: 'gunner',
    name: 'Pháo Thủ',
    description: 'Tập trung vào sát thương súng',
    talents: [
      {
        id: 'gun_damage_1',
        name: 'Sát Thương Súng +',
        description: 'Tăng 5% sát thương súng',
        branch: 'gunner',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { gunDamage: 5 }, // 5% per rank
      },
      {
        id: 'armor_piercing',
        name: 'Bắn Xuyên Giáp',
        description: 'Học kỹ năng Bắn Xuyên Giáp',
        branch: 'gunner',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['gun_damage_1'],
        effects: {},
        grantsSkill: 'armor_piercing_shot',
      },
      {
        id: 'rapid_fire',
        name: 'Bắn Liên Hoàn',
        description: 'Giảm 10% thời gian nạp đạn',
        branch: 'gunner',
        tier: 3,
        maxRank: 3,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['armor_piercing'],
        effects: { reloadSpeed: 10 },
      },
      {
        id: 'headshot_mastery',
        name: 'Bắn Chính Xác',
        description: 'Tăng 15% tỉ lệ chí mạng với súng',
        branch: 'gunner',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['rapid_fire'],
        effects: { gunCritChance: 15 },
      },
    ],
  },
  {
    id: 'mechanic',
    name: 'Thợ Máy',
    description: 'Tập trung vào Robot và Trụ',
    talents: [
      {
        id: 'turret_durability',
        name: 'Trụ Bền Hơn',
        description: 'Trụ có thêm 10% HP',
        branch: 'mechanic',
        tier: 1,
        maxRank: 3,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { turretHp: 10 }, // 10% per rank
      },
      {
        id: 'guardian_robot',
        name: 'Robot Hộ Vệ',
        description: 'Triệu hồi Robot Hộ Vệ',
        branch: 'mechanic',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 3,
        levelRequired: 20,
        prerequisiteTalents: ['turret_durability'],
        effects: {},
        grantsSkill: 'summon_guardian',
      },
      {
        id: 'improved_ai',
        name: 'Trí Tuệ Nhân Tạo Nâng Cao',
        description: 'Robot và Trụ tăng 20% sát thương',
        branch: 'mechanic',
        tier: 3,
        maxRank: 3,
        pointsInBranchRequired: 8,
        levelRequired: 30,
        prerequisiteTalents: ['guardian_robot'],
        effects: { summonDamage: 20 },
      },
      {
        id: 'deploy_fortress',
        name: 'Triển Khai Pháo Đài',
        description: 'Học kỹ năng triển khai pháo đài di động',
        branch: 'mechanic',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['improved_ai'],
        effects: {},
        grantsSkill: 'deploy_fortress',
      },
    ],
  },
  {
    id: 'demolition',
    name: 'Chuyên Gia Thuốc Nổ',
    description: 'Tập trung vào lựu đạn và bẫy',
    talents: [
      {
        id: 'grenade_damage',
        name: 'Sát Thương Lựu Đạn +',
        description: 'Tăng 10% sát thương lựu đạn',
        branch: 'demolition',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { grenadeDamage: 10 }, // 10% per rank
      },
      {
        id: 'mine_trap',
        name: 'Đặt Bẫy Mìn',
        description: 'Học kỹ năng Đặt Bẫy Mìn',
        branch: 'demolition',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['grenade_damage'],
        effects: {},
        grantsSkill: 'place_mine',
      },
      {
        id: 'blast_radius',
        name: 'Bán Kính Nổ Rộng',
        description: 'Tăng 25% phạm vi nổ',
        branch: 'demolition',
        tier: 3,
        maxRank: 2,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['mine_trap'],
        effects: { explosionRadius: 25 },
      },
      {
        id: 'napalm_strike',
        name: 'Ném Bom Napalm',
        description: 'Học kỹ năng ném bom napalm gây sát thương theo thời gian',
        branch: 'demolition',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['blast_radius'],
        effects: {},
        grantsSkill: 'napalm_strike',
      },
    ],
  },
];

export const MUTANT_WARRIOR_TALENTS: TalentBranch[] = [
  {
    id: 'berserker',
    name: 'Cuồng Chiến',
    description: 'Tập trung vào sát thương và tốc độ tấn công',
    talents: [
      {
        id: 'rage_damage',
        name: 'Sát Thương Cuồng Nộ +',
        description: 'Tăng 5% sát thương khi có Nộ đầy',
        branch: 'berserker',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { rageDamage: 5 },
      },
      {
        id: 'rampage',
        name: 'Cuồng Loạn',
        description: 'Học kỹ năng Cuồng Loạn',
        branch: 'berserker',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['rage_damage'],
        effects: {},
        grantsSkill: 'rampage',
      },
      {
        id: 'bloodlust',
        name: 'Khát Máu',
        description: 'Hồi 3% HP tối đa mỗi khi giết địch',
        branch: 'berserker',
        tier: 3,
        maxRank: 3,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['rampage'],
        effects: { killHeal: 3 },
      },
      {
        id: 'titan_strength',
        name: 'Sức Mạnh Titan',
        description: 'Tăng 30% sát thương và 20% HP tối đa',
        branch: 'berserker',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['bloodlust'],
        effects: { damage: 30, maxHp: 20 },
      },
    ],
  },
  {
    id: 'guardian',
    name: 'Vệ Binh',
    description: 'Tập trung vào phòng thủ và bảo vệ',
    talents: [
      {
        id: 'armor_boost',
        name: 'Giáp Cứng +',
        description: 'Tăng 5% giáp',
        branch: 'guardian',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { armor: 5 },
      },
      {
        id: 'shield_wall',
        name: 'Tường Khiên',
        description: 'Học kỹ năng Tường Khiên',
        branch: 'guardian',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['armor_boost'],
        effects: {},
        grantsSkill: 'shield_wall',
      },
      {
        id: 'iron_skin',
        name: 'Da Sắt',
        description: 'Giảm 8% sát thương nhận vào',
        branch: 'guardian',
        tier: 3,
        maxRank: 3,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['shield_wall'],
        effects: { damageReduction: 8 },
      },
      {
        id: 'unbreakable_will',
        name: 'Ý Chí Bất Khuất',
        description: 'Miễn dịch với hiệu ứng khống chế khi HP dưới 30%',
        branch: 'guardian',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['iron_skin'],
        effects: { ccImmunityLowHp: true },
      },
    ],
  },
  {
    id: 'intimidation',
    name: 'Hù Dọa',
    description: 'Tập trung vào kiểm soát và làm suy yếu kẻ thù',
    talents: [
      {
        id: 'fear_duration',
        name: 'Hù Dọa Lâu Hơn +',
        description: 'Tăng 20% thời gian hù dọa',
        branch: 'intimidation',
        tier: 1,
        maxRank: 3,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { fearDuration: 20 },
      },
      {
        id: 'terrifying_roar',
        name: 'Gầm Kinh Hồn',
        description: 'Học kỹ năng Gầm Kinh Hồn',
        branch: 'intimidation',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 3,
        levelRequired: 20,
        prerequisiteTalents: ['fear_duration'],
        effects: {},
        grantsSkill: 'terrifying_roar',
      },
      {
        id: 'crushing_blow',
        name: 'Đòn Nghiền Nát',
        description: 'Tấn công có 15% khả năng làm choáng 2 giây',
        branch: 'intimidation',
        tier: 3,
        maxRank: 2,
        pointsInBranchRequired: 8,
        levelRequired: 30,
        prerequisiteTalents: ['terrifying_roar'],
        effects: { stunChance: 15 },
      },
      {
        id: 'war_cry',
        name: 'Hét Chiến',
        description: 'Học kỹ năng hét chiến làm giảm 30% sát thương của địch',
        branch: 'intimidation',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['crushing_blow'],
        effects: {},
        grantsSkill: 'war_cry',
      },
    ],
  },
];

export const RUNE_HISTORIAN_TALENTS: TalentBranch[] = [
  {
    id: 'restoration',
    name: 'Phục Hồi',
    description: 'Tập trung vào hồi máu và hỗ trợ đồng đội',
    talents: [
      {
        id: 'healing_power',
        name: 'Sức Mạnh Hồi Phục +',
        description: 'Tăng 10% hiệu quả hồi máu',
        branch: 'restoration',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { healingPower: 10 },
      },
      {
        id: 'mass_heal',
        name: 'Hồi Máu Tập Thể',
        description: 'Học kỹ năng Hồi Máu Tập Thể',
        branch: 'restoration',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['healing_power'],
        effects: {},
        grantsSkill: 'mass_heal',
      },
      {
        id: 'rejuvenation',
        name: 'Phục Sinh',
        description: 'Hồi 2% HP tối đa mỗi 3 giây',
        branch: 'restoration',
        tier: 3,
        maxRank: 3,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['mass_heal'],
        effects: { hpRegen: 2 },
      },
      {
        id: 'divine_intervention',
        name: 'Can Thiệp Thần Thánh',
        description: 'Học kỹ năng cứu mạng đồng minh khỏi cái chết',
        branch: 'restoration',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['rejuvenation'],
        effects: {},
        grantsSkill: 'divine_intervention',
      },
    ],
  },
  {
    id: 'buff',
    name: 'Tăng Cường',
    description: 'Tập trung vào buff và tăng sức mạnh đồng đội',
    talents: [
      {
        id: 'buff_duration',
        name: 'Buff Lâu Hơn +',
        description: 'Tăng 20% thời gian buff',
        branch: 'buff',
        tier: 1,
        maxRank: 3,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { buffDuration: 20 },
      },
      {
        id: 'arcane_power',
        name: 'Sức Mạnh Bí Thuật',
        description: 'Học kỹ năng Sức Mạnh Bí Thuật',
        branch: 'buff',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 3,
        levelRequired: 20,
        prerequisiteTalents: ['buff_duration'],
        effects: {},
        grantsSkill: 'arcane_power',
      },
      {
        id: 'empowerment',
        name: 'Trao Quyền',
        description: 'Buff tăng thêm 15% hiệu quả',
        branch: 'buff',
        tier: 3,
        maxRank: 3,
        pointsInBranchRequired: 8,
        levelRequired: 30,
        prerequisiteTalents: ['arcane_power'],
        effects: { buffPower: 15 },
      },
      {
        id: 'heroism',
        name: 'Anh Hùng Ca',
        description: 'Học kỹ năng tăng 40% sát thương cho toàn đội 15 giây',
        branch: 'buff',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['empowerment'],
        effects: {},
        grantsSkill: 'heroism',
      },
    ],
  },
  {
    id: 'debuff',
    name: 'Suy Yếu',
    description: 'Tập trung vào debuff và giảm sức mạnh kẻ thù',
    talents: [
      {
        id: 'curse_power',
        name: 'Sức Mạnh Lời Nguyền +',
        description: 'Tăng 10% hiệu quả debuff',
        branch: 'debuff',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { cursePower: 10 },
      },
      {
        id: 'hex_of_weakness',
        name: 'Lời Nguyền Yếu Đuối',
        description: 'Học kỹ năng Lời Nguyền Yếu Đuối',
        branch: 'debuff',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['curse_power'],
        effects: {},
        grantsSkill: 'hex_of_weakness',
      },
      {
        id: 'amplify_curse',
        name: 'Khuếch Đại Lời Nguyền',
        description: 'Lời nguyền lan sang 1 mục tiêu gần đó',
        branch: 'debuff',
        tier: 3,
        maxRank: 2,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['hex_of_weakness'],
        effects: { curseSpread: 1 },
      },
      {
        id: 'doom',
        name: 'Tận Thế',
        description: 'Học kỹ năng gây 200% sát thương sau 8 giây',
        branch: 'debuff',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['amplify_curse'],
        effects: {},
        grantsSkill: 'doom',
      },
    ],
  },
];

export const STALKER_TALENTS: TalentBranch[] = [
  {
    id: 'assassination',
    name: 'Ám Sát',
    description: 'Tập trung vào sát thương bùng nổ và chí mạng',
    talents: [
      {
        id: 'critical_chance',
        name: 'Tỉ Lệ Chí Mạng +',
        description: 'Tăng 5% tỉ lệ chí mạng',
        branch: 'assassination',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { critChance: 5 },
      },
      {
        id: 'backstab',
        name: 'Đâm Lén',
        description: 'Học kỹ năng Đâm Lén',
        branch: 'assassination',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['critical_chance'],
        effects: {},
        grantsSkill: 'backstab',
      },
      {
        id: 'critical_damage',
        name: 'Sát Thương Chí Mạng +',
        description: 'Tăng 20% sát thương chí mạng',
        branch: 'assassination',
        tier: 3,
        maxRank: 3,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['backstab'],
        effects: { critDamage: 20 },
      },
      {
        id: 'execute',
        name: 'Hành Quyết',
        description: 'Học kỹ năng hành quyết, gây 300% sát thương với mục tiêu dưới 20% HP',
        branch: 'assassination',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['critical_damage'],
        effects: {},
        grantsSkill: 'execute',
      },
    ],
  },
  {
    id: 'shadow',
    name: 'Bóng Đêm',
    description: 'Tập trung vào tàng hình và né tránh',
    talents: [
      {
        id: 'dodge_chance',
        name: 'Né Tránh +',
        description: 'Tăng 5% tỉ lệ né tránh',
        branch: 'shadow',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { dodgeChance: 5 },
      },
      {
        id: 'vanish',
        name: 'Biến Mất',
        description: 'Học kỹ năng Biến Mất',
        branch: 'shadow',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['dodge_chance'],
        effects: {},
        grantsSkill: 'vanish',
      },
      {
        id: 'shadow_step',
        name: 'Bước Bóng Tối',
        description: 'Giảm 30% thời gian hồi kỹ năng di chuyển',
        branch: 'shadow',
        tier: 3,
        maxRank: 2,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['vanish'],
        effects: { mobilityCD: 30 },
      },
      {
        id: 'shadow_dance',
        name: 'Vũ Điệu Bóng Tối',
        description: 'Học kỹ năng tàng hình và tăng 50% tốc độ tấn công',
        branch: 'shadow',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['shadow_step'],
        effects: {},
        grantsSkill: 'shadow_dance',
      },
    ],
  },
  {
    id: 'poison',
    name: 'Độc Dược',
    description: 'Tập trung vào độc và sát thương theo thời gian',
    talents: [
      {
        id: 'poison_damage',
        name: 'Sát Thương Độc +',
        description: 'Tăng 10% sát thương độc',
        branch: 'poison',
        tier: 1,
        maxRank: 5,
        pointsInBranchRequired: 0,
        levelRequired: 10,
        effects: { poisonDamage: 10 },
      },
      {
        id: 'deadly_poison',
        name: 'Độc Chết Người',
        description: 'Học kỹ năng Độc Chết Người',
        branch: 'poison',
        tier: 2,
        maxRank: 1,
        pointsInBranchRequired: 5,
        levelRequired: 20,
        prerequisiteTalents: ['poison_damage'],
        effects: {},
        grantsSkill: 'deadly_poison',
      },
      {
        id: 'venom_spread',
        name: 'Lan Tỏa Nọc Độc',
        description: 'Độc lan sang kẻ địch gần đó khi mục tiêu chết',
        branch: 'poison',
        tier: 3,
        maxRank: 2,
        pointsInBranchRequired: 10,
        levelRequired: 30,
        prerequisiteTalents: ['deadly_poison'],
        effects: { poisonSpread: true },
      },
      {
        id: 'plague_strike',
        name: 'Đòn Dịch Bệnh',
        description: 'Học kỹ năng gây bệnh, giảm 50% hồi máu của mục tiêu',
        branch: 'poison',
        tier: 4,
        maxRank: 1,
        pointsInBranchRequired: 15,
        levelRequired: 40,
        prerequisiteTalents: ['venom_spread'],
        effects: {},
        grantsSkill: 'plague_strike',
      },
    ],
  },
];

export function getTalentsByClass(classId: string): TalentBranch[] {
  switch (classId) {
    case 'scrap_engineer':
      return SCRAP_ENGINEER_TALENTS;
    case 'mutant_warrior':
      return MUTANT_WARRIOR_TALENTS;
    case 'rune_historian':
      return RUNE_HISTORIAN_TALENTS;
    case 'stalker':
      return STALKER_TALENTS;
    default:
      return [];
  }
}

export function getTalentById(classId: string, talentId: string): TalentNode | null {
  const branches = getTalentsByClass(classId);
  for (const branch of branches) {
    const talent = branch.talents.find(t => t.id === talentId);
    if (talent) return talent;
  }
  return null;
}
